"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Contractor_1 = require("./Contractor");
var FTE_1 = require("./FTE");
var EmployeeController_1 = require("./EmployeeController");
var PartTimeEmployee_1 = require("./PartTimeEmployee");
var teo = new FTE_1.default();
var ti = new Contractor_1.default();
var tun = new PartTimeEmployee_1.default();
teo.setBonus();
ti.setBonus();
tun.setBonus();
var totalSalary = EmployeeController_1.default.getTotalSalary([teo, ti, tun]);
console.log("Total Salary: ", totalSalary);
console.log("Teo bonus:", teo.getBonus());
console.log("Ti bonus: ".concat(ti.getBonus()));
console.log("Tun bonus: ".concat(tun.getBonus()));
